import avatarImage1 from '../assets/Arthur_Horpo_Marx-Groucho_Marx brother.jpeg';
import avatarImage2 from '../assets/Dan-Wynn_Bill-Gates-Time_Magazine.jpg';
import avatarImage3 from '../assets/Dan Wyn-Hitchcock.jpeg';
import avatarImage4 from '../assets/Dan-Wynn_Dolly-Parton.jpg';
import avatarImage5 from '../assets/Dan_Wynn_Leonard_Nimoy_Mr_Spark.jpg';
import avatarImage6 from '../assets/Dan_Wynn_Steinem_Hughes.jpg';
import avatarImage7 from '../assets/DanWynn-Al-Pacino.jpeg';
import avatarImage8 from '../assets/DanWynn-ChevyChase.jpeg';
import avatarImage9 from '../assets/DanWynn-DustinHoffman.jpeg';
import avatarImage10 from '../assets/Dan_Wynn_Carol_Burnett.jpg';

const metaData = [
  {
    imageUrl: avatarImage1,
    seller: 'Hossein123',
    subject: 'Alfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 10,
  },
  {
    imageUrl: avatarImage2,
    seller: 'Pavel123',
    subject: 'Blfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 16,
  },
  {
    imageUrl: avatarImage3,
    seller: 'Bossein123',
    subject: 'Clfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 17,
  },
  {
    imageUrl: avatarImage4,
    seller: 'Justin123',
    subject: 'Dlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 23,
  },
  {
    imageUrl: avatarImage5,
    seller: 'Mark123',
    subject: 'Flfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 89,
  },
  {
    imageUrl: avatarImage6,
    seller: 'Bill123',
    subject: 'Hlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 47,
  },
  {
    imageUrl: avatarImage7,
    seller: 'Messi123',
    subject: 'Ylfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 44,
  },
  {
    imageUrl: avatarImage8,
    seller: 'Rhino123',
    subject: 'Mlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 2,
  },
  {
    imageUrl: avatarImage9,
    seller: 'Ronaldo123',
    subject: 'Klfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 9,
  },
  {
    imageUrl: avatarImage10,
    seller: 'Suares123',
    subject: 'Tlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 50,
  },
  {
    imageUrl: avatarImage1,
    seller: 'Neimar123',
    subject: 'Olfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 40,
  },
  {
    imageUrl: avatarImage2,
    seller: 'Ronaldiho123',
    subject: 'Plfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 30,
  },
  {
    imageUrl: avatarImage3,
    seller: 'Zidan123',
    subject: 'Bomb Hitchcock',
    photographer: 'Dan Wynn',
    price: 28,
  },
  {
    imageUrl: avatarImage4,
    seller: 'Ozil123',
    subject: 'Orange Hitchcock',
    photographer: 'Dan Wynn',
    price: 25,
  },
  {
    imageUrl: avatarImage5,
    seller: 'Muler123',
    subject: 'Drop Hitchcock',
    photographer: 'Dan Wynn',
    price: 18,
  },
  {
    imageUrl: avatarImage6,
    seller: 'Savi123',
    subject: 'Alfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 67,
  },
  {
    imageUrl: avatarImage7,
    seller: 'Alonxa123',
    subject: 'Sandokan Hitchcock',
    photographer: 'Dan Wynn',
    price: 51,
  },
  {
    imageUrl: avatarImage8,
    seller: 'Casilas123',
    subject: 'Cool Hitchcock',
    photographer: 'Dan Wynn',
    price: 42,
  },
  {
    imageUrl: avatarImage9,
    seller: 'Ramos123',
    subject: 'Ox Hitchcock',
    photographer: 'Dan Wynn',
    price: 15,
  },
  {
    imageUrl: avatarImage10,
    seller: 'Hossein123',
    subject: 'Ryan Hitchcock',
    photographer: 'Dan Wynn',
    price: 88,
  },
  {
    imageUrl: avatarImage1,
    seller: 'Yasin123',
    subject: 'Cow Hitchcock',
    photographer: 'Dan Wynn',
    price: 56,
  },
  {
    imageUrl: avatarImage2,
    seller: 'Beckam123',
    subject: 'Pig Hitchcock',
    photographer: 'Dan Wynn',
    price: 19,
  },
  {
    imageUrl: avatarImage3,
    seller: 'Alexander123',
    subject: 'Dog Hitchcock',
    photographer: 'Dan Wynn',
    price: 7,
  },
  {
    imageUrl: avatarImage4,
    seller: 'Cal123',
    subject: 'Cat Hitchcock',
    photographer: 'Dan Wynn',
    price: 13,
  },
  {
    imageUrl: avatarImage5,
    seller: 'Close123',
    subject: 'Wolf Hitchcock',
    photographer: 'Dan Wynn',
    price: 5,
  },
  {
    imageUrl: avatarImage6,
    seller: 'Iguain123',
    subject: 'Fox Hitchcock',
    photographer: 'Dan Wynn',
    price: 34,
  },
  {
    imageUrl: avatarImage7,
    seller: 'Maradona123',
    subject: 'Rabbit Hitchcock',
    photographer: 'Dan Wynn',
    price: 22,
  },
  {
    imageUrl: avatarImage8,
    seller: 'Pele123',
    subject: 'Woolf Hitchcock',
    photographer: 'Dan Wynn',
    price: 6,
  },
  {
    imageUrl: avatarImage9,
    seller: 'Kaka123',
    subject: 'Wlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 22,
  },
  {
    imageUrl: avatarImage10,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage1,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage2,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage3,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage4,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage5,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage6,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage7,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage8,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage9,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage10,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage1,
    seller: 'Adriano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 20,
  },
  {
    imageUrl: avatarImage2,
    seller: 'Aano123',
    subject: 'Qlfred Hitchcock',
    photographer: 'Dan Wynn',
    price: 100,
  },
];

export default metaData;
